CREATE DATABASE IF NOT EXISTS wtw;
GRANT ALL PRIVILEGES ON wtw.* TO wtw@localhost IDENTIFIED BY 'wtw';

USE wtw;

DROP TABLE IF EXISTS WEATHERCONDITION;
DROP TABLE IF EXISTS ATMOSPHERE;
DROP TABLE IF EXISTS WIND;
DROP TABLE IF EXISTS WEATHER;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS SOURCE_PARAMETER;
DROP TABLE IF EXISTS SOURCE;

CREATE TABLE IF NOT EXISTS SOURCE (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME INT(8) UNSIGNED, 
  URL VARCHAR(255) NOT NULL,
  INDEX SOURCE_NAME_INDEX (NAME)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS SOURCE_PARAMETER(
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  VALUE VARCHAR(255) NOT NULL,
  SOURCE_ID INT(8)UNSIGNED NOT NULL,
  FOREIGN KEY(SOURCE_ID) REFERENCES SOURCE(ID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS LOCATION (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  WOEID INT(8) UNSIGNED, 
  ZIP VARCHAR(255) NOT NULL,
  CITY VARCHAR(255),
  COUNTRY VARCHAR(255),
  REGION VARCHAR(255),
  SOURCE_ID INT(8)UNSIGNED NOT NULL,
  FOREIGN KEY(SOURCE_ID) REFERENCES SOURCE(ID),
  INDEX LOCATION_WOEID_INDEX (WOEID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS WEATHER (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATE TIMESTAMP,
  SOURCE_ID INT(8)UNSIGNED NOT NULL,
  LOCATION_ID INT(8)UNSIGNED NOT NULL,
  FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(ID),
  FOREIGN KEY(SOURCE_ID) REFERENCES SOURCE(ID),
  INDEX WEATHER_LOCATION_INDEX (LOCATION_ID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS WIND (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CHILL VARCHAR(255),
  DIRECTION VARCHAR(255),
  SPEED VARCHAR(255),
  WEATHER_ID INT(8)UNSIGNED NOT NULL,
  FOREIGN KEY (WEATHER_ID) REFERENCES WEATHER(ID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS ATMOSPHERE (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  HUMIDITY VARCHAR(255),
  PRESSURE VARCHAR(255),
  RISING VARCHAR(255),
  VISIBILITY VARCHAR(255),
  WEATHER_ID INT(8) UNSIGNED NOT NULL,
  FOREIGN KEY (WEATHER_ID) REFERENCES WEATHER(ID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS WEATHERCONDITION (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODE VARCHAR(255),
  DATE TIMESTAMP,
  TEMP VARCHAR(255),
  TEXT VARCHAR(255),
  WEATHER_ID INT(8) UNSIGNED NOT NULL,
  FOREIGN KEY (WEATHER_ID) REFERENCES WEATHER(ID)
) engine=InnoDB;