CREATE DATABASE IF NOT EXISTS wtw;
GRANT ALL PRIVILEGES ON wtw.* TO wtw@localhost IDENTIFIED BY 'wtw';

USE wtw;

DROP TABLE IF EXISTS WEATHERCONDITION;
DROP TABLE IF EXISTS PRECIPITATION;
DROP TABLE IF EXISTS ATMOSPHERE;
DROP TABLE IF EXISTS WIND;
DROP TABLE IF EXISTS WEATHERFORECAST;
DROP TABLE IF EXISTS WEATHER;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS SOURCE_PARAMETER;
DROP TABLE IF EXISTS SOURCE;

CREATE TABLE IF NOT EXISTS SOURCE (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME INT(8) UNSIGNED, 
  URL VARCHAR(255) NOT NULL,
  INDEX SOURCE_NAME_INDEX (NAME)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS SOURCE_PARAMETER(
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  VALUE VARCHAR(255) NOT NULL,
  SOURCE_ID INT(8)UNSIGNED NOT NULL,
  FOREIGN KEY(SOURCE_ID) REFERENCES SOURCE(ID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS LOCATION (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  WOEID INT(8) UNSIGNED, 
  POSTAL VARCHAR(255) NOT NULL,
  TYPE VARCHAR(255),
  ALTITUDE DOUBLE NOT NULL,
  LATITUDE DOUBLE NOT NULL,
  LONGITUDE DOUBLE NOT NULL,
  GEOBASE VARCHAR(255),
  GEOBASEID INT(8) UNSIGNED NOT NULL,
  COUNTRY VARCHAR(255),
  REGION VARCHAR(255),
  SOURCE_ID INT(8)UNSIGNED NOT NULL,
  FOREIGN KEY(SOURCE_ID) REFERENCES SOURCE(ID),
  INDEX LOCATION_WOEID_INDEX (WOEID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS WEATHER (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  WRITETIME TIMESTAMP,
  SOURCETIME TIMESTAMP,
  REGION INT(8) UNSIGNED NOT NULL,
  SOURCE VARCHAR(255) NOT NULL,
  FORECAST BOOLEAN,
  INDEX REGION (REGION)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS WEATHERFORECAST (
  WEATHER_ID INT(8)UNSIGNED NOT NULL,
  PERIODFROM TIMESTAMP,
  PERIODTO TIMESTAMP
) engine=InnoDB;


CREATE TABLE IF NOT EXISTS WIND (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CHILL DOUBLE NOT NULL,
  DIRECTION VARCHAR(255),
  SPEED DOUBLE NOT NULL,
  WEATHER_ID INT(8)UNSIGNED NOT NULL,
  FOREIGN KEY (WEATHER_ID) REFERENCES WEATHER(ID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS ATMOSPHERE (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  HUMIDITY DOUBLE NOT NULL,
  PRESSURE DOUBLE NOT NULL,
  RISING VARCHAR(255),
  VISIBILITY DOUBLE NOT NULL,
  WEATHER_ID INT(8) UNSIGNED NOT NULL,
  FOREIGN KEY (WEATHER_ID) REFERENCES WEATHER(ID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS PRECIPITATION (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TEXT VARCHAR(255),
  RATE DOUBLE NOT NULL,
  CODE VARCHAR(255),
  WEATHER_ID INT(8) UNSIGNED NOT NULL,
  FOREIGN KEY (WEATHER_ID) REFERENCES WEATHER(ID)
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS WEATHERCONDITION (
  ID INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODE VARCHAR(255),
  FROMTIME TIMESTAMP,
  TOTIME TIMESTAMP,
  MINTEMP DOUBLE NOT NULL,
  MAXTEMP DOUBLE NOT NULL,
  TEXT VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  ICON VARCHAR(255),
  WEATHER_ID INT(8) UNSIGNED NOT NULL,
  FOREIGN KEY (WEATHER_ID) REFERENCES WEATHER(ID)
) engine=InnoDB;

COMMIT;